name: Rust CI/CD

on:
   push:
      branches:
         - main
   pull_request:
      branches:
         - main

jobs:
   build:
      name: Build for Linux and Windows
      runs-on: ubuntu-latest
      strategy:
         matrix:
            target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu]

      steps:
         # Step 1: Checkout the code
         - name: Checkout code
           uses: actions/checkout@v2

         # Step 2: Install Rust toolchain
         - name: Set up Rust
           uses: actions-rs/toolchain@v1
           with:
              toolchain: stable
              target: ${{ matrix.target }}
              override: true

         # Step 3: Install mingw-w64 for Windows cross-compilation
         - name: Install mingw-w64 (Windows target only)
           if: matrix.target == 'x86_64-pc-windows-gnu'
           run: |
              sudo apt-get update
              sudo apt-get install -y mingw-w64

         # Step 4: Build the project
         - name: Build
           run: cargo build --release --target ${{ matrix.target }}

         # Step 5: Upload build artifacts
         - name: Upload build artifact
           uses: actions/upload-artifact@v2
           with:
              name: ${{ matrix.target }}-build
              path:
                 target/${{ matrix.target }}/release/key_repeat_configurator${{ matrix.target ==
                 'x86_64-pc-windows-gnu' && '.exe' || '' }}
